name: food_packet
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  google_nav_bar: ^5.0.6
  adobe_xd: ^2.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  introduction_slider: ^2.0.1
  carousel_slider: ^4.2.1
  pinput: ^2.2.21
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_fonts: ^4.0.3
  fluttertoast: ^8.1.2
  cloud_firestore: ^4.3.1
  favorite_button: ^0.0.4
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  http: ^0.13.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

 
  assets:
    - images/
  #